Repository netlify/gatsby-plugin-netlify, pull requests merged in 2022-04, with the labels that each got.

#109 chore: convert repository to Typescript
  package.json
  src/__tests__/__snapshots__/build-headers-program.ts.snap
  src/__tests__/build-headers-program.ts
  src/__tests__/gatsby-node.ts
  src/__tests__/tsconfig.json
  src/build-headers-program.ts
  src/constants.ts
  src/create-redirects.ts
  src/gatsby-node.ts
  src/plugin-data.ts
  tsconfig.json
  yarn.lock
Labels: type: chore, automerge

#116 chore: fix linting errors
  .eslintrc.js
  .prettierrc.js
  src/__tests__/gatsby-node.ts
  src/constants.ts
  src/create-redirects.ts
  src/gatsby-node.ts
  src/plugin-data.ts
  yarn.lock
Labels: type: chore, automerge

#117 feat: Add support for advanced redirect types
  src/__tests__/__snapshots__/create-redirects.ts.snap
  src/__tests__/build-headers-program.ts
  src/__tests__/create-redirects.ts
  src/__tests__/helpers.ts
  src/create-redirects.ts
Labels: type: feature, automerge

#120 fix: redirect named splat filesystem routes correctly for SSR/DSG pages
  src/gatsby-node.ts
Labels: type: bug, automerge
