Repository netlify/gatsby-plugin-netlify, pull requests merged in 2022-01, with the labels that each got.

#54 chore(docs): Add section explaining when the plugin is not needed
  README.md
Labels: type: chore

#56 chore: add Kodiak
  .github/kodiak.toml
Labels: type: chore

#57 chore: use Netlify linting rules
  .eslintrc.js
  .github/.kodiak.toml
  .github/workflows/test.yml
  .prettierrc.js
  package.json
  src/__tests__/build-headers-program.js
  src/__tests__/gatsby-node.js
  src/build-headers-program.js
  src/create-redirects.js
  src/gatsby-node.js
  yarn.lock
Labels: type: chore

#59 chore: update readme
  README.md
Labels: type: chore, automerge

#65 feat: disable Netlify functions if not needed
  src/gatsby-node.js
Labels: type: feature, automerge
